#!/bin/sh
SERA_HOME=`dirname $0`
cd $SERA_HOME
export SERA_HOME=`pwd`
echo $SERA_HOME
touch $SERA_HOME/config/Local.def
imake -I./config
make Makefile
make Makefiles
make includes
make depend
make install
